services:
  recicle_me_caduser:
    container_name: recicle_me_cadusers
    image: cadusers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        postgresqldb:
          condition: service_healthy
    environment:
      POSTGRES_HOST: postgresqldb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
  postgresqldb:
    container_name: postgresqldb
    image: postgres:15-alpine3.17
    ports:
      - "5433:5432"
    user: postgres
    environment:
      POSTGRES_HOST: postgresqldb
      POSTGRES_DB: recicle_me
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 2
    volumes:
      - postgresqldb:/var/lib/postgresql/data
  recicle_me_front:
    container_name: recicle_me_front
    build:
      context: ../recicle_me_front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
        - recicle_me_caduser
volumes:
  postgresqldb:

#networks:
#  default:
#    name: recicle_me_network